Медучереждения
Vikort/ostis-geography pull request #18
Opened 2022-02-08 20:20 UTC by Chudopal

Добалено 500 медучереждений.
Александр Ч. - 821701
Алина Н. - 821704
Добвалено 500 понятий и транслятор для понятий вместо агента.
Путь к транслятору: ostis-geography/kb/d/Belarus_hospitals/scrapper
ЯП - Python

2022-02-10 19:22 UTC, Vikort requested changes
Исправить комментарий и перенести из папки d в папку с областью или районом в котором эти больницы находятся

2022-02-10 19:22 UTC, Vikort commented on kb/d/Belarus_hospitals/1_terapevticheskij_korpus.scs
> +=>nrel_search_area: Belarus;;
Область поиска Беларусь указана по умолчанию, либо указывайте как минимум область, либо не указывайте это отношение.
```suggestion
(* <- lang_ru;; <- name_ru;; <- name;;*);;
```

2022-02-10 22:07 UTC, Chudopal commented on kb/d/Belarus_hospitals/1_terapevticheskij_korpus.scs
> +=>nrel_search_area: Belarus;;
Переместил понятия, удалил nrel_search_area

2022-02-23 17:12 UTC, Vikort reviewed
Сделайте так, чтобы база собиралась.
ошибки из-за некорректных системных идентификаторов(из-за пробелов, ковычек и т.д.)
переместите транслятор в папку tools в корне репо

2022-02-28 16:05 UTC, Chudopal commented
> Сделайте так, чтобы база собиралась. ошибки из-за некорректных системных идентификаторов(из-за пробелов, ковычек и т.д.) переместите транслятор в папку tools в корне репо

Сделал проверку на символы, перенес папку

2022-03-02 20:56 UTC, Chudopal commented
Мы добавили интерфейс, но мы просто переделали этот пример https://github.com/ostis-apps/ostis-example-app/tree/0.5.0/interface%2Fsc-web-extensions
У нас возникла какая-то ошибка при сборке базы:
./build_kb.sh: line 11: sc-machine/bin/sc-builder: No such file or directory
Пытались на разных осях: Ubuntu. MacOs - ошибка онда и та же.
Совсем не поняли как сделать doCommand верно, потому сделали просто через жсовскую exec в другом потоке.

2022-03-07 13:46 UTC, Vikort approved these changes
Треться часть принята
Вмержу сам после исправления замечаний.

2022-03-07 13:46 UTC, Vikort commented on kb/openstreetmap_view.scs
> +ui_external_languages
убрать из коммитов

2022-07-23 19:09 UTC, merged