дадаў 100 гродзенскіх вуліц
Vikort/ostis-geography pull request #2
Opened 2022-02-04 21:34 UTC by Vlashious

Дадаў 100 гродзденскіх вуліц па шаблоне

2022-02-07 05:47 UTC, SHtress requested changes
Fix newline at the end of the file, update Pull request information by adding info about your group, name and theme, for example like here https://github.com/Vikort/ostis-geography/pull/3 or here https://github.com/Vikort/ostis-geography/pull/4

2022-02-07 07:45 UTC, Vikort commented
Смени название пра на свою тему, добавь для GitHub пустые строки в конце файлов, перемести папку hrodna_streets в папку kb/section_subjdomain_openstreetmap/subject_domain_belarus/области/hrodna_region

2022-02-07 07:47 UTC, Vikort commented
Часть с базой принята, пр сольем мы, после выполнения всех частей.

2022-02-08 20:27 UTC, Vlashious commented
Дадаў транслятар для вуліц, які можа быць ужыты для ўсіх гарадоў Беларусі. На дадзены момант знаходзіцца ў problem_solver/dotnet/street_parser

2022-02-10 17:58 UTC, SHtress approved these changes
Перенеси транслятор из problem-solver в tools в корне проекта. Мы сами замержим.

2022-02-21 19:35 UTC, Vikort reviewed
Вторая часть принята

2022-03-06 14:57 UTC, Vikort approved these changes
Все принято
пр смержу сам

2022-07-23 19:04 UTC, merged