945 companies added
Vikort/ostis-geography pull request #21
Opened 2022-02-09 12:14 UTC by unicode256

2022-02-10 19:50 UTC, Vikort requested changes
Пофиксить сборку базы
падает сборка из-за `-` в системных идентификаторах

2022-02-16 11:19 UTC, unicode256 commented
> Пофиксить сборку базы падает сборка из-за `-` в системных идентификаторах в описании указать авторов

fixed

2022-02-23 17:16 UTC, SHtress requested changes
Добавьте документацию, убрать комментарии и убрать абсолютные пути

2022-02-24 09:24 UTC, unicode256 commented
> Добавьте документацию, убрать комментарии и убрать абсолютные пути

fixed

2022-03-01 20:00 UTC, Vikort commented
Первая и вторая часть приняты

2022-03-09 09:41 UTC, Vikort commented
Либо скрины как работает интерфейс, либо интсуркцию по запуску, у нас не удалось запустить ваш интерфейс

2022-03-09 12:09 UTC, unicode256 commented
> Либо скрины как работает интерфейс, либо интсуркцию по запуску, у нас не удалось запустить ваш интерфейс

переделали интерфейс

2022-03-16 08:08 UTC, SHtress approved these changes

2022-12-11 21:22 UTC, closed without merging