kb hardware store supplies Dmitruk Alexey 821703
Vikort/ostis-geography pull request #26
Opened 2022-02-09 17:23 UTC by zhoskiy

2022-02-15 10:37 UTC, SHtress requested changes

2022-02-15 10:37 UTC, SHtress commented on instance/caparol-318.scs
> +caparol-318
Тире нельзя использовать для системных, меняйте на нижнее подчеркивание, проверяйте сборку базы
```suggestion
caparol_318
```

2022-02-16 17:06 UTC, zhoskiy commented on instance/caparol-318.scs
> +caparol-318
исправил

2022-02-23 17:32 UTC, SHtress requested changes
Должно быть на ветке pis и понятия должны лежать уже в kb

2022-03-01 20:26 UTC, zhoskiy commented
> Должно быть на ветке pis и понятия должны лежать уже в kb

Пересоздал пр https://github.com/Vikort/ostis-geography/pull/59

2022-03-03 19:38 UTC, closed without merging