Driving Schools
Vikort/ostis-geography pull request #33
Opened 2022-02-09 19:48 UTC by Lonexera

Толкачева Т.А., гр. 821704
Стасько В.С., гр. 821703

2022-02-15 13:43 UTC, SHtress requested changes

2022-02-15 13:43 UTC, SHtress commented on kb/section_subjdomain_openstreetmap/concepts/concept_drivers_license.scs
> +concept_driver;
```suggestion
concept_driver
```

2022-02-15 13:43 UTC, SHtress commented on kb/section_subjdomain_openstreetmap/subject_domain_belarus/driving_schools/Minsk/driving_schools_minsk.scs
> +nrel_failure_rate
```suggestion

```

2022-02-15 13:43 UTC, SHtress commented on kb/section_subjdomain_openstreetmap/subject_domain_belarus/driving_schools/Minsk/driving_schools_minsk.scs
> +=>nrel_failure_rate: 92;;
https://www.openstreetmap.org/node/2626398547#map=19/53.94641/27.69688
Сами школы на карте есть но у вас не отображаются исправьте

2022-02-15 13:43 UTC, SHtress commented on kb/section_subjdomain_openstreetmap/relations/nrel_raiting_in_tp.scs
> +<|- transitive_relation;;
Новую строку в конце файла

2022-02-23 18:03 UTC, Vikort reviewed
Как определить где какой агент?
![image](https://user-images.githubusercontent.com/43759605/155379630-222585c5-408c-4c73-8400-2a231af2a088.png)
Первая часть принята

2022-02-23 18:03 UTC, Vikort commented on kb/section_subjdomain_openstreetmap/subject_domain_belarus/driving_schools/Minsk/driving_schools_minsk.scs
> +    [12
```suggestion
    [12]
```

2022-02-23 19:35 UTC, Lonexera commented
исправлено

2022-03-01 20:14 UTC, Vikort commented
Вторая часть принята

2022-03-07 14:36 UTC, Vikort approved these changes
Третья часть принята

2022-03-16 08:11 UTC, SHtress approved these changes

2022-03-22 13:06 UTC, closed without merging