Add VUZi Belarusi
Vikort/ostis-geography pull request #36
Opened 2022-02-09 20:33 UTC by MitrafanauYahor

Митрофанов Е.В. 821702

2022-02-15 19:12 UTC, Vikort requested changes
перепроверь названия на карте, а не офицаиальные названия, если их совсем нет на карте, то все ок

2022-02-15 19:12 UTC, Vikort commented on kb/VUZi/Akademija_Ministerstva_vnutrennih_del_Respubliki_Belarus'.scs
> +                =>nrel_city:Минск;;
поменять везде
```suggestion
                =>nrel_city: minsk;;
```

2022-02-15 19:12 UTC, Vikort commented on kb/VUZi/Akademija_Ministerstva_vnutrennih_del_Respubliki_Belarus'.scs
> +                [Академия Министерства внутренних дел Республики Беларусь]
не отображается на карте

2022-02-15 19:12 UTC, Vikort commented on kb/VUZi/BIP_—_Universitet_prava_i_sotsial'no-informatsionnyh_tehnologij.scs
> +                [БИП — Университет права и социально-информационных технологий]
не отображается на карте

2022-03-16 08:11 UTC, SHtress approved these changes

2023-03-24 14:24 UTC, closed without merging