KB Новицкий, Сапежинский, 821703 Estates of Belarus
Vikort/ostis-geography pull request #42
Opened 2022-02-09 21:15 UTC by rotsky

added mnogo estates

2022-02-15 20:09 UTC, Vikort reviewed
Не все усадьбы отображаются на [карте](https://www.openstreetmap.org/)
не трогать не ваши файлы!!!
описание областей, районов, городов и т.п., если это необходимо, делать в отдельном файле, в нужной папке в соответствии с иерархией директорий

2022-02-15 20:09 UTC, Vikort commented on kb/openstreetmap_view.scs
> +ui_external_languages
убрать этот файл из коммитов

2022-02-15 20:09 UTC, Vikort commented on kb/section_subjdomain_openstreetmap/subject_domain_belarus/Belarus.scs
> -    (* <- name;; *);
вернуть как было и не трогать этот файл

2022-02-15 20:09 UTC, Vikort commented on kb/section_subjdomain_openstreetmap/subject_domain_belarus/estates/Vitebsk_estates/estates_of_Vitebsk_region..scs
> +    Vitebsk_region;
системные идентификаторы с маленькой буквы
```suggestion
    vitebsk_region;
```

2022-02-15 20:09 UTC, Vikort commented on kb/section_subjdomain_openstreetmap/subject_domain_belarus/estates/Vitebsk_estates/estates_of_Vitebsk_region..scs
> +    [4 сезона]
нашло аграрный магазин в Минске, а не усадьбу в витебской области

2022-02-23 18:13 UTC, Vikort requested changes
Не собирается база

2022-03-04 07:45 UTC, SHtress requested changes
Уберите не ваши файлы из ПР
Есвли вводите отношение или понятие, которого нет в базе, опишите его
Добавьте документацию к агентам, обратите в ней внимание на их запуск/
Проверьте работают ли  агенты, мне не удалось запустить их и получить нужный результат
Усадьбы не отображаются на карте, проверьте name и посмотрите в примерах

2022-03-09 09:02 UTC, Vikort reviewed
Первая и вторая части приняты
Уберите не ваши файлы из пра, еще раз об это писать не будем, без обьяснений запросим изменения

2022-07-04 15:24 UTC, closed without merging