add 100 secondary special education
Vikort/ostis-geography pull request #46
Opened 2022-02-10 15:33 UTC by Santmus

100 средне специальных учебных заведений
821701 Казаченко Е.А
Извиняюсь, за то, что поздно. Проблема с git была

2022-02-15 20:29 UTC, Vikort requested changes
Поправить форматирование, невозможно прочесть файл.

2022-02-15 20:29 UTC, Vikort commented on kb/openstreetmap_view.scs
> +ui_external_languages
убрать этот файл из коммитов

2022-02-15 20:29 UTC, Vikort commented on kb/secondary_special_ schools/objects/Brest_oblast/secondary_special_educational_breastkaya_oblast.scs
> +        *);
к идентификатору, по которому нужно искать объект на карте, привязать name.
```suggestion
brest_bisness_and_prav_college
=> nrel_main_idtf:
    [Колледж бизнеса и права]
    (* <- lang_ru;; <- name;; *);
```

2022-02-16 09:44 UTC, Santmus commented on kb/openstreetmap_view.scs
> +ui_external_languages
откатил этот состояние файла до fork

2022-02-19 22:26 UTC, Santmus commented
Добавлены 3 агента:
1. Агент, который находит ССУЗы в опр.городе
2. Агент, который находит ССУЗы в опр.области
3. Агент, который находит ССУЗы с опр. датой открытия уч.заведения

2022-02-23 18:25 UTC, SHtress requested changes
Добавьте документацию, включающую в себя запуск агента

2022-02-23 23:10 UTC, Santmus commented
Добавлены скриншоты и описания для каждого агента

2022-03-01 18:46 UTC, SHtress reviewed
Принято

2022-03-02 09:23 UTC, Santmus commented
Добавлен интерфейс и инструкция как его запустить:
Там реализовано 3 агента + доб.кнопка которая позволяет перейти на понятие "ССУЗ" + ссылка на странциу в википедии
В инструкции показан пример только одного агента

2022-03-07 15:07 UTC, Vikort approved these changes
Третья часть принята

2022-03-08 17:20 UTC, Santmus commented
Забыл добавить в комит файлы отвечающие за интерфейс. Работа интерфейса не изменилась

2022-03-16 08:19 UTC, SHtress approved these changes

2022-09-11 09:19 UTC, closed without merging