Bury 821702 KB Coffee Houses
Vikort/ostis-geography pull request #49
Opened 2022-02-13 00:19 UTC by VladikBrown

2022-02-15 20:45 UTC, Vikort requested changes
Перепроверь названия на карте

2022-02-15 20:45 UTC, Vikort commented on kb/coffee_houses/Art-Kofejnja Belyj Chemodan_36_.scs
> +       (* <- lang_ru;; <- name_ru;;*);
Добавь name к идентификаторам, по которым должен осуществляться поиск по карте
```suggestion
       [Арт-кофейня "Белый чемодан"]
       (* <- lang_ru;; <- name_ru;; <- name;;*);
```
Белый чемодан на [карте](https://www.openstreetmap.org/node/4964569002)

2022-02-16 20:00 UTC, VladikBrown commented on kb/coffee_houses/Art-Kofejnja Belyj Chemodan_36_.scs
> +       (* <- lang_ru;; <- name_ru;;*);
вроде исправил))0

2022-02-23 18:19 UTC, Vikort requested changes

2022-02-23 18:19 UTC, Vikort commented on kb/coffee_houses/Kofejnja_Mesto_25_.scs
> +       $;;
не собирается база

2022-07-04 15:29 UTC, closed without merging