Банки: понятия + агенты
Vikort/ostis-geography pull request #56
Opened 2022-02-16 20:58 UTC by DamnedDeus

Шкут Р.В., гр. 821703
тема - банковские отделения

Содержит исправленные понятия и три агента поиска (по городу, по типу (concept_bank, concept_atm и т.д.) и по брэнду)

2022-02-23 18:57 UTC, SHtress requested changes
Не работают агенты

2022-02-24 12:58 UTC, DamnedDeus commented
Всё работает. Проверено неоднократно.

2022-02-24 13:29 UTC, DamnedDeus commented
![brand1](https://user-images.githubusercontent.com/45313704/155533120-79018ae9-46dd-44e0-a1ec-531ee80ce1c7.png)
![brand2](https://user-images.githubusercontent.com/45313704/155533127-a8e2a0db-c97f-4789-bdb3-3bfe1b1b4bda.png)
![brand3](https://user-images.githubusercontent.com/45313704/155533128-21099703-a812-4aaa-b1e9-fca35b37c6d4.png)
![brand4](https://user-images.githubusercontent.com/45313704/155533129-fdc28c70-ce5d-4922-bea1-b0770e4b003b.png)
![brand5](https://user-images.githubusercontent.com/45313704/155533131-750139d2-c350-497c-a022-0d7c73facce6.png)
![city1](https://user-images.githubusercontent.com/45313704/155533135-9bdef62a-7c15-4a59-b492-81373f1609eb.png)
![city2](https://user-images.githubusercontent.com/45313704/155533136-c4044094-9be3-4ead-9303-e0a3d73eaa5b.png)
![city3](https://user-images.githubusercontent.com/45313704/155533137-ee95b698-0cd1-435e-89c5-54df7c85c6d4.png)
![city4](https://user-images.githubusercontent.com/45313704/155533139-67e86de5-4d3b-4136-a756-d6774e51c32e.png)
![city5](https://user-images.githubusercontent.com/45313704/155533144-1c710b98-3b92-44a4-8514-d913b48c6886.png)
![type1](https://user-images.githubusercontent.com/45313704/155533147-8ebefb0d-a390-4076-bda6-a7ffd4c81679.png)
![type2](https://user-images.githubusercontent.com/45313704/155533150-430bebff-a58e-40b9-a2c1-ad33ddfd1335.png)
![type3](https://user-images.githubusercontent.com/45313704/155533153-77483ebd-fb71-41de-9235-1d527ea91f91.png)
![type4](https://user-images.githubusercontent.com/45313704/155533157-13d5ec31-7458-4d7c-8c08-ec9ce95fc8de.png)

2022-02-24 13:31 UTC, DamnedDeus commented
Поиск по брэнду:
![brand4](https://user-images.githubusercontent.com/45313704/155533506-2ff5d592-9886-4d41-ab6d-00ecf0fad2b5.png)
![brand5](https://user-images.githubusercontent.com/45313704/155533508-68040b19-2955-4275-9509-fdd24eea0cc8.png)
![brand1](https://user-images.githubusercontent.com/45313704/155533510-df17fc98-fbf8-485c-a337-1dbf681ab687.png)
![brand2](https://user-images.githubusercontent.com/45313704/155533512-86e7f98f-e62c-4421-ac83-dceb20074a50.png)
![brand3](https://user-images.githubusercontent.com/45313704/155533515-0b76ef56-e44e-4d17-9a91-641fa47c991f.png)

2022-02-24 13:32 UTC, DamnedDeus commented
Поиск по городу:
![city4](https://user-images.githubusercontent.com/45313704/155533565-6d77512b-25c1-46a8-888b-e32be7959866.png)
![city5](https://user-images.githubusercontent.com/45313704/155533567-894429ba-9ac3-4838-b43d-520f91b63dad.png)
![city1](https://user-images.githubusercontent.com/45313704/155533568-6217b9b6-d100-4c30-b3da-f66a000ff8cc.png)
![city2](https://user-images.githubusercontent.com/45313704/155533572-a45586cc-0f2b-4469-a95d-ac9e4d291765.png)
![city3](https://user-images.githubusercontent.com/45313704/155533575-fe7d885a-3ba4-4b27-8734-3f01f4e256c4.png)

2022-02-24 13:32 UTC, DamnedDeus commented
Поиск по типу:
![type1](https://user-images.githubusercontent.com/45313704/155533607-67a44c37-39b4-4bcc-9091-8232dd09ce3b.png)
![type2](https://user-images.githubusercontent.com/45313704/155533611-59b80cd5-acf9-413d-ae70-2fb6f162d67f.png)
![type3](https://user-images.githubusercontent.com/45313704/155533614-e48e6f86-2d5c-4f02-802d-bba8ee52f93e.png)
![type4](https://user-images.githubusercontent.com/45313704/155533616-10363233-06c3-4986-abf0-d40d7af0e23e.png)

2022-02-24 13:40 UTC, DamnedDeus commented
Добавил агенты в CMakeLists, должно заработать.

2022-03-05 17:06 UTC, DamnedDeus commented
Добавлен интерфейс, обновлены скрипты установки и документация.

2022-03-07 15:23 UTC, Vikort approved these changes
Вторая и третья части приняты
Смержу пр после исправления замечаний

2022-03-07 15:23 UTC, Vikort commented on README.md
> -## Version 0.6.0
не трогать этот файл, вернуть как было, создать свой ридми

2022-03-07 23:49 UTC, DamnedDeus commented
Исправлено, если я правильно понял замечания.

2022-03-16 08:21 UTC, SHtress approved these changes

2022-07-23 19:16 UTC, merged